const words = [
  { word: "abacaxi", clue: "Fruta tropical" },
{ word: "elefante", clue: "Animal de grande porte com tromba longa" },
{ word: "computador", clue: "Dispositivo eletrônico" },
{ word: "girafa", clue: "Animal alto, com pescoço longo" },
{ word: "chocolate", clue: "Doce feito de cacau" },
{ word: "piano", clue: "Instrumento musical com teclas" },
{ word: "tigre", clue: "Felino selvagem" },
{ word: "esmeralda", clue: "Tipo de pedra preciosa" },
{ word: "navio", clue: "Embarcação no mar" },
{ word: "telefone", clue: "Dispositivo de comunicação" },
{ word: "floresta", clue: "Área com muitas árvores" },
{ word: "quadrado", clue: "Figura geométrica de quatro lados" },
{ word: "foguete", clue: "Veículo espacial" },
{ word: "sorvete", clue: "Doce gelado" },
{ word: "bicicleta", clue: "Veículo de duas rodas" },
{ word: "avião", clue: "Meio de transporte aéreo" },
{ word: "macaco", clue: "Primate arbóreo" },
{ word: "raios", clue: "Descargas elétricas na atmosfera" },
{ word: "montanha", clue: "Elevação natural da terra" },
{ word: "vela", clue: "Objeto para iluminação" },
{ word: "cachorro", clue: "Animal de estimação, conhecido por sua lealdade" },
{ word: "lua", clue: "Satélite natural da Terra" },
{ word: "gato", clue: "Animal de estimação, felino" },
{ word: "carro", clue: "Veículo automotor de quatro rodas" },
{ word: "flor", clue: "Parte colorida das plantas" },
{ word: "livro", clue: "Objeto com páginas que contém texto" },
{ word: "escola", clue: "Instituição para aprendizado" },
{ word: "leão", clue: "Rei da selva, felino" },
{ word: "sol", clue: "Estrela que ilumina o nosso sistema solar" },
{ word: "cachoeira", clue: "Queda de água de grande altura" },
{ word: "foto", clue: "Imagem capturada por uma câmera" },
{ word: "relógio", clue: "Instrumento para medir o tempo" },
{ word: "papagaio", clue: "Ave colorida e falante" },
{ word: "mar", clue: "Corpo de água salgada que cobre grande parte da Terra" },
{ word: "tartaruga", clue: "Animal com casco duro" },
{ word: "livraria", clue: "Estabelecimento onde se vendem livros" },
{ word: "vampiro", clue: "Ser mitológico que se alimenta de sangue" },
{ word: "foca", clue: "Mamífero marinho" },
{ word: "ilha", clue: "Porção de terra cercada por água" },
{ word: "flamengo", clue: "Time de futebol do Rio de Janeiro" },
{ word: "estátua", clue: "Escultura de uma pessoa ou animal" },
{ word: "sereia", clue: "Ser mitológico com corpo de peixe e cabeça de mulher" },
{ word: "guitarra", clue: "Instrumento musical de cordas" },
{ word: "serpente", clue: "Animal reptiliano, similar à cobra" },
{ word: "relâmpago", clue: "Descarga elétrica durante tempestades" },
{ word: "gelo", clue: "Água congelada" },
{ word: "arco-íris", clue: "Fenômeno óptico com cores visíveis no céu" },
{ word: "esquilo", clue: "Roedor conhecido por armazenar nozes" },
{ word: "aviário", clue: "Espaço para criação de aves" },
{ word: "cebola", clue: "Legume com cheiro forte e sabor picante" },
{ word: "médico", clue: "Profissional da saúde" },
{ word: "pinguim", clue: "Ave não voadora adaptada ao frio" },
{ word: "fruta", clue: "Alimento doce e natural das plantas" },
{ word: "caneta", clue: "Instrumento para escrever com tinta" },
{ word: "forno", clue: "Equipamento usado para cozinhar ou assar alimentos" },
{ word: "cavalo", clue: "Animal de grande porte usado para montar" },
{ word: "relatório", clue: "Documento que apresenta informações ou resultados" },
{ word: "janela", clue: "Abertura em uma parede para ventilação e luz" },
{ word: "computação", clue: "Campo relacionado ao uso de computadores e tecnologia" },
{ word: "código", clue: "Sistema de sinais ou símbolos usados para comunicação" },
{ word: "tomate", clue: "Fruta vermelha usada frequentemente em saladas" },
{ word: "vento", clue: "Movimento do ar na atmosfera" },
{ word: "nuvem", clue: "Vapor de água condensado na atmosfera" },
{ word: "universo", clue: "Tudo o que existe, incluindo estrelas, planetas e galáxias" },
{ word: "chave", clue: "Objeto usado para abrir fechaduras" },
{ word: "balão", clue: "Objeto inflável usado para transporte ou diversão" },
{ word: "pescador", clue: "Pessoa que pesca peixes" },
{ word: "jardim", clue: "Área cultivada com plantas e flores" },
{ word: "pedra", clue: "Material sólido encontrado na natureza" },
{ word: "fada", clue: "Ser mitológico com poderes mágicos" },
{ word: "bicho-preguiça", clue: "Animal conhecido por seu ritmo lento" },
{ word: "copo", clue: "Recipiente usado para beber líquidos" },
{ word: "pneu", clue: "Parte do veículo que entra em contato com o solo" },
{ word: "areia", clue: "Grãos pequenos de rochas, encontrados nas praias" },
{ word: "coelho", clue: "Animal pequeno, com orelhas grandes" },
{ word: "rádio", clue: "Dispositivo usado para ouvir transmissões sonoras" },
{ word: "tábua", clue: "Superfície plana de madeira" },
{ word: "mãe", clue: "Pessoa que gera e cuida de um filho" },
{ word: "pai", clue: "Pessoa que é responsável pela criação de um filho" },
{ word: "brinquedo", clue: "Objeto usado para diversão, especialmente por crianças" },
{ word: "porta", clue: "Objeto móvel usado para fechar uma abertura" },
{ word: "olho", clue: "Órgão sensorial usado para ver" },
{ word: "estrela", clue: "Corpo celeste que emite luz própria" },
{ word: "páscoa", clue: "Festa cristã que celebra a ressurreição de Cristo" },
{ word: "janela", clue: "Abertura em um prédio ou casa para iluminação e ventilação" },
{ word: "bola", clue: "Objeto redondo usado em diversos jogos" },
{ word: "medalha", clue: "Premiação geralmente de metal" },
{ word: "torneio", clue: "Competição com várias etapas e jogadores" },
{ word: "marte", clue: "Planeta vermelho, conhecido como o planeta dos sonhos" },
{ word: "borboleta", clue: "Inseto com asas coloridas" },
{ word: "pássaro", clue: "Ave que voa e tem penas" },
{ word: "refrigerante", clue: "Bebida gaseificada e doce" },
{ word: "bola", clue: "Objeto esférico usado em diversos esportes" },
{ word: "zebra", clue: "Animal de pele listrada e parente do cavalo" },
{ word: "abóbora", clue: "Fruto com casca dura e polpa macia" },
{ word: "caverna", clue: "Espaço subterrâneo natural" },
{ word: "guitarra", clue: "Instrumento musical de cordas" },
{ word: "orquestra", clue: "Conjunto musical formado por vários instrumentos" },
{ word: "soluço", clue: "Contração involuntária do diafragma" },
{ word: "banco", clue: "Instituição financeira que lida com dinheiro" }

];

export default function getWord() {
  const index = Math.floor(Math.random() * words.length);
  return words[index];
}
